# Site settings
# Meta tags
title: Grantmakers.io - A Community Project
description: Quickly find data on 70,000 grantmaking institutions in the US. An open source project from your friends at SmarterGiving.

# Jekyll settings
baseurl: # Leave this blank unless your site is located on a subpath, e.g. /blog
url: https://www.grantmakers.io # Typically http://www.yourdomain.org
sass:
  sass_dir: assets/css/_sass

# Google Analytics
google-analytics: UA-84268197-1

# Algolia Link
algolia-link: http://goto.algolia.com/l/139121/2017-10-24/26gc84

# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules
  - algolia/
  - data/ #Note: does not affect _data folder